/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/alto-car.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/alto-car.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 109.58, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <group position={[0.817, 1.662, -0.642]}>
            <group position={[-0.001, -0.001, -0.132]}>
              <mesh geometry={nodes.wheel_steering0_0.geometry} material={materials['steering.005']} />
              <mesh geometry={nodes.wheel_steering1_0.geometry} material={materials['steering.006']} />
              <mesh geometry={nodes.wheel_steering2_0.geometry} material={materials['steering.007']} />
              <mesh geometry={nodes.wheel_wheel2_0.geometry} material={materials['wheel.006']} />
              <mesh geometry={nodes.wheel_wheel4_0.geometry} material={materials['wheel.001']} />
              <mesh geometry={nodes.wheel_wheel5_0.geometry} material={materials['wheel.003']} />
            </group>
            <group position={[-0.001, -2.986, -0.132]}>
              <mesh geometry={nodes.wheel001_steering0_0.geometry} material={materials['steering.005']} />
              <mesh geometry={nodes.wheel001_steering1_0.geometry} material={materials['steering.006']} />
              <mesh geometry={nodes.wheel001_steering2_0.geometry} material={materials['steering.007']} />
              <mesh geometry={nodes.wheel001_wheel2_0.geometry} material={materials['wheel.006']} />
              <mesh geometry={nodes.wheel001_wheel4_0.geometry} material={materials['wheel.001']} />
              <mesh geometry={nodes.wheel001_wheel5_0.geometry} material={materials['wheel.003']} />
            </group>
            <group position={[-1.637, -2.986, -0.132]} rotation={[-Math.PI, 0, 0]} scale={-1}>
              <mesh geometry={nodes.wheel002_steering0_0.geometry} material={materials['steering.005']} />
              <mesh geometry={nodes.wheel002_steering1_0.geometry} material={materials['steering.006']} />
              <mesh geometry={nodes.wheel002_steering2_0.geometry} material={materials['steering.007']} />
              <mesh geometry={nodes.wheel002_wheel2_0.geometry} material={materials['wheel.006']} />
              <mesh geometry={nodes.wheel002_wheel4_0.geometry} material={materials['wheel.001']} />
              <mesh geometry={nodes.wheel002_wheel5_0.geometry} material={materials['wheel.003']} />
            </group>
            <group position={[-1.637, 0, -0.132]} rotation={[-Math.PI, 0, 0]} scale={-1}>
              <mesh geometry={nodes.wheel003_steering0_0.geometry} material={materials['steering.005']} />
              <mesh geometry={nodes.wheel003_steering1_0.geometry} material={materials['steering.006']} />
              <mesh geometry={nodes.wheel003_steering2_0.geometry} material={materials['steering.007']} />
              <mesh geometry={nodes.wheel003_wheel2_0.geometry} material={materials['wheel.006']} />
              <mesh geometry={nodes.wheel003_wheel4_0.geometry} material={materials['wheel.001']} />
              <mesh geometry={nodes.wheel003_wheel5_0.geometry} material={materials['wheel.003']} />
            </group>
          </group>
          <group position={[0, -1.39, 0.682]}>
            <mesh geometry={nodes.glass_dash5_0.geometry} material={materials['dash.007']} />
            <mesh geometry={nodes.glass_glass002_0.geometry} material={materials['glass.006']} />
            <mesh geometry={nodes.glass_glass3_0.geometry} material={materials['glass.007']} />
            <mesh geometry={nodes.glass_primary_0.geometry} material={materials['primary.001']} />
            <mesh geometry={nodes.glass_steering1_0.geometry} material={materials['steering.006']} />
            <mesh geometry={nodes.glass_steering2_0.geometry} material={materials['steering.007']} />
            <mesh geometry={nodes.light_right_rear_light_0.geometry} material={materials['right_rear_light.001']} />
          </group>
          <group position={[-0.838, 1.172, -0.023]}>
            <mesh geometry={nodes.door003_chassis3_0.geometry} material={materials['chassis.001']} />
            <mesh geometry={nodes.door003_dash3_0.geometry} material={materials['dash.008']} />
            <mesh geometry={nodes.door003_dash5_0.geometry} material={materials['dash.007']} />
            <mesh geometry={nodes.door003_glass001_0.geometry} material={materials['glass.005']} />
            <mesh geometry={nodes.door003_mate8_0.geometry} material={materials['mate.006']} />
            <mesh geometry={nodes.door003_primary_0.geometry} material={materials['primary.001']} />
            <mesh geometry={nodes.door003_seat0_0.geometry} material={materials['seat.001']} />
          </group>
          <group position={[-0.846, -0.075, -0.028]}>
            <mesh geometry={nodes.door005_chassis3_0.geometry} material={materials['chassis.001']} />
            <mesh geometry={nodes.door005_dash3_0.geometry} material={materials['dash.008']} />
            <mesh geometry={nodes.door005_dash5_0.geometry} material={materials['dash.007']} />
            <mesh geometry={nodes.door005_dore21_0.geometry} material={materials['dore2.002']} />
            <mesh geometry={nodes.door005_glass001_0.geometry} material={materials['glass.005']} />
            <mesh geometry={nodes.door005_primary_0.geometry} material={materials['primary.001']} />
            <mesh geometry={nodes.door005_seat0_0.geometry} material={materials['seat.001']} />
          </group>
          <group position={[0.824, 1.172, -0.034]}>
            <mesh geometry={nodes.door_chassis3_0.geometry} material={materials['chassis.001']} />
            <mesh geometry={nodes.door_dash3_0.geometry} material={materials['dash.008']} />
            <mesh geometry={nodes.door_dash5_0.geometry} material={materials['dash.007']} />
            <mesh geometry={nodes.door_glass001_0.geometry} material={materials['glass.005']} />
            <mesh geometry={nodes.door_mate8_0.geometry} material={materials['mate.006']} />
            <mesh geometry={nodes.door_primary_0.geometry} material={materials['primary.001']} />
            <mesh geometry={nodes.door_seat0_0.geometry} material={materials['seat.001']} />
          </group>
          <group position={[0.843, -0.075, -0.029]}>
            <mesh geometry={nodes.door004_chassis3_0.geometry} material={materials['chassis.001']} />
            <mesh geometry={nodes.door004_dash3_0.geometry} material={materials['dash.008']} />
            <mesh geometry={nodes.door004_dash5_0.geometry} material={materials['dash.007']} />
            <mesh geometry={nodes.door004_dore21_0.geometry} material={materials['dore2.002']} />
            <mesh geometry={nodes.door004_glass001_0.geometry} material={materials['glass.005']} />
            <mesh geometry={nodes.door004_primary_0.geometry} material={materials['primary.001']} />
            <mesh geometry={nodes.door004_seat0_0.geometry} material={materials['seat.001']} />
          </group>
          <group position={[0, -0.003, 0.032]}>
            <mesh geometry={nodes.EXT_chassis3_0.geometry} material={materials['chassis.001']} />
            <mesh geometry={nodes.EXT_primary_0.geometry} material={materials['primary.001']} />
          </group>
          <mesh geometry={nodes.chassis_chass1_0.geometry} material={materials['chass.002']} />
          <mesh geometry={nodes.chassis_chassis2_0.geometry} material={materials['chassis.004']} />
          <mesh geometry={nodes.chassis_chassis3_0.geometry} material={materials['chassis.001']} />
          <mesh geometry={nodes.chassis_chassis3_0001.geometry} material={materials['chassis.001']} />
          <mesh geometry={nodes.chassis_dash2_0.geometry} material={materials['dash.006']} />
          <mesh geometry={nodes.chassis_dash4_0.geometry} material={materials['dash.001']} />
          <mesh geometry={nodes.chassis_glass001_0.geometry} material={materials['glass.005']} />
          <mesh geometry={nodes.chassis_glass_0.geometry} material={materials['glass.004']} />
          <mesh geometry={nodes.chassis_mate2_0.geometry} material={materials['mate.001']} />
          <mesh geometry={nodes.chassis_seat11_0.geometry} material={materials['seat1.003']} />
          <mesh geometry={nodes.chassis_seat12_0.geometry} material={materials['seat1.004']} />
          <mesh geometry={nodes.chassis_seat0_0.geometry} material={materials['seat.001']} />
          <mesh geometry={nodes.chassis_third_0.geometry} material={materials['third.001']} />
          <mesh name="chassis_primary_0" geometry={nodes.chassis_primary_0.geometry} material={materials['primary.001']} morphTargetDictionary={nodes.chassis_primary_0.morphTargetDictionary} morphTargetInfluences={[props.damageValue]} />
          <mesh geometry={nodes.dash_chassis3_0.geometry} material={materials['chassis.001']} />
          <mesh geometry={nodes.dash_dash2_0.geometry} material={materials['dash.006']} />
          <mesh geometry={nodes.dash_dash3_0.geometry} material={materials['dash.008']} />
          <mesh geometry={nodes.dash_dash4_0.geometry} material={materials['dash.001']} />
          <mesh geometry={nodes.dash_dash5_0.geometry} material={materials['dash.007']} />
          <mesh geometry={nodes.dash_seat0_0.geometry} material={materials['seat.001']} />
          <mesh geometry={nodes.dash_third_0.geometry} material={materials['third.001']} />
          <mesh geometry={nodes.dore_chassis2_0.geometry} material={materials['chassis.004']} />
          <mesh geometry={nodes.dore_chassis3_0.geometry} material={materials['chassis.001']} />
          <mesh geometry={nodes.dore_dash2_0.geometry} material={materials['dash.006']} />
          <mesh geometry={nodes.dore_dash4_0.geometry} material={materials['dash.001']} />
          <mesh geometry={nodes.dore_dash5_0.geometry} material={materials['dash.007']} />
          <mesh geometry={nodes.dore_dore21_0.geometry} material={materials['dore2.002']} />
          <mesh geometry={nodes.dore_primary_0.geometry} material={materials['primary.001']} />
          <mesh geometry={nodes.LIGHT_left_front_light_0.geometry} material={materials['left_front_light.001']} />
          <mesh geometry={nodes.LIGHT_left_rear_light_0.geometry} material={materials['left_rear_light.001']} />
          <mesh geometry={nodes.LIGHT_right_front_light_0.geometry} material={materials['right_front_light.001']} />
          <mesh geometry={nodes.LIGHT_right_rear_light_0.geometry} material={materials['right_rear_light.001']} />
          <mesh geometry={nodes.mate_chassis3_0.geometry} material={materials['chassis.001']} />
          <mesh geometry={nodes.mate_dash2_0.geometry} material={materials['dash.006']} />
          <mesh geometry={nodes.mate_dash3_0.geometry} material={materials['dash.008']} />
          <mesh geometry={nodes.mate_dash4_0.geometry} material={materials['dash.001']} />
          <mesh geometry={nodes.mate_dash5_0.geometry} material={materials['dash.007']} />
          <mesh geometry={nodes.mate_mate2_0.geometry} material={materials['mate.001']} />
          <mesh geometry={nodes.mate_mate4_0.geometry} material={materials['mate.005']} />
          <mesh geometry={nodes.mate_mate8_0.geometry} material={materials['mate.006']} />
          <mesh geometry={nodes.mate_mate9_0.geometry} material={materials['mate.003']} />
          <mesh geometry={nodes.mate_seat0_0.geometry} material={materials['seat.001']} />
          <mesh geometry={nodes.steering_steering0_0.geometry} material={materials['steering.005']} />
          <mesh geometry={nodes.steering_steering1_0.geometry} material={materials['steering.006']} />
          <mesh geometry={nodes.steering_steering2_0.geometry} material={materials['steering.007']} />
          <mesh geometry={nodes.steering_steering3_0.geometry} material={materials['steering.004']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/alto-car.glb')