/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/damaged-car.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/damaged-car.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['wheel-back-left'].geometry} material={materials.colormap} position={[0.3, 0.3, -0.66]} />
      <mesh geometry={nodes['wheel-back-right'].geometry} material={materials.colormap} position={[-0.3, 0.3, -0.66]} />
      <mesh geometry={nodes['wheel-front-left'].geometry} material={materials.colormap} position={[0.3, 0.3, 0.66]} />
      <mesh geometry={nodes['wheel-front-right'].geometry} material={materials.colormap} position={[-0.3, 0.3, 0.66]} />
      <mesh name="body" geometry={nodes.body.geometry} material={materials.colormap} morphTargetDictionary={nodes.body.morphTargetDictionary} morphTargetInfluences={[props.damageValue]} position={[0, 0.15, -0.025]} />
    </group>
  )
}

useGLTF.preload('./damaged-car.glb')
