/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Swift-car.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Swift-car.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 73.1, 0]} rotation={[-1.586, 0, 0]} scale={100}>
          <group position={[-0.005, -0.002, 0]}>
            <group position={[0.005, -1.705, 0.386]}>
              <mesh geometry={nodes.boot_grille2_0.geometry} material={materials['grille.2']} />
              <mesh geometry={nodes.boot_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.boot_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.boot_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
            </group>
            <group position={[0.005, 1.744, -0.466]}>
              <mesh geometry={nodes.chassis_chassis1_0.geometry} material={materials['chassis.1']} />
              <mesh geometry={nodes.chassis_chassis3_0.geometry} material={materials['chassis.3']} />
              <mesh geometry={nodes.chassis_chassis4_0.geometry} material={materials['chassis.4']} />
              <mesh geometry={nodes.chassis_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.chassis_movsteer_104_0.geometry} material={materials['movsteer_1.0.4']} />
              <mesh geometry={nodes.chassis_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.dashboard_chassis1_0.geometry} material={materials['chassis.1']} />
              <mesh geometry={nodes.dashboard_chassis4_0.geometry} material={materials['chassis.4']} />
              <mesh geometry={nodes.dashboard_mb010_0.geometry} material={materials['mb01.0']} />
              <mesh geometry={nodes.dashboard_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} position={[0.062, -0.107, 0.095]} />
              <mesh geometry={nodes.dashboard_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.dashboard_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.dashboard_movsteer_104_0.geometry} material={materials['movsteer_1.0.4']} />
              <mesh geometry={nodes.dashboard_movsteer_106_0.geometry} material={materials['movsteer_1.0.6']} />
              <mesh geometry={nodes.dashboard_speedometer3_0.geometry} material={materials['speedometer.3']} />
              <mesh geometry={nodes.dashboard_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.dashboard_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.radio_glass_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.screen_glass_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.foglight_f_mb010_0.geometry} material={materials['mb01.0']} />
              <mesh geometry={nodes.foglight_glass_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.foglight_l_foglight_l_0.geometry} material={materials.foglight_l} />
              <mesh geometry={nodes.foglight_r_foglight_r_0.geometry} material={materials.foglight_r} />
              <mesh geometry={nodes.grille_grille2_0.geometry} material={materials['grille.2']} />
              <mesh geometry={nodes.grille_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.grille_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} position={[-0.079, -0.055, 0.156]} />
              <mesh geometry={nodes.headlight_glass_glass002_0.geometry} material={materials['glass.002']} />
              <mesh geometry={nodes.headlight_glass_headlight_glass1_0.geometry} material={materials['headlight_glass.1']} />
              <mesh geometry={nodes.headlight_mesh_mb010_0.geometry} material={materials['mb01.0']} />
              <mesh geometry={nodes.mb01_chassis4_0.geometry} material={materials['chassis.4']} />
              <mesh geometry={nodes.mb01_mb010_0.geometry} material={materials['mb01.0']} />
              <mesh geometry={nodes.mb01_mb014_0.geometry} material={materials['mb01.4']} />
              <mesh geometry={nodes.mb01_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.mb01_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.mb02_mb010_0.geometry} material={materials['mb01.0']} />
              <mesh geometry={nodes.mb02_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.headlight_led_right_front_light_0.geometry} material={materials.right_front_light} />
              <mesh geometry={nodes.indicator_lf001_indicator_lf_0.geometry} material={materials.indicator_lf} />
              <mesh geometry={nodes.indicator_rf001_indicator_rr_0.geometry} material={materials.indicator_rr} />
              <mesh geometry={nodes.mb04_chassis1_0.geometry} material={materials['chassis.1']} />
              <mesh geometry={nodes.mb04_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.mb04_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.mb04_movsteer_104_0.geometry} material={materials['movsteer_1.0.4']} />
              <mesh geometry={nodes.mb04_primary_0001.geometry} material={materials.primary} />
              <mesh geometry={nodes.mb04_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh name="mb04_primary_0" geometry={nodes.mb04_primary_0.geometry} material={materials.primary} morphTargetDictionary={nodes.mb04_primary_0.morphTargetDictionary} morphTargetInfluences={[props.damageValue]} />
              <mesh geometry={nodes.mb05_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.mb06_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.mb07_chassis1_0.geometry} material={materials['chassis.1']} />
              <mesh geometry={nodes.mb07_chassis4_0.geometry} material={materials['chassis.4']} />
              <mesh geometry={nodes.mb07_mb010_0.geometry} material={materials['mb01.0']} />
              <mesh geometry={nodes.mb07_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.mb07_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.mb07_movsteer_104_0.geometry} material={materials['movsteer_1.0.4']} />
              <mesh geometry={nodes.mb07_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.mb07_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.mb0111_movsteer_104_0.geometry} material={materials['movsteer_1.0.4']} />
              <mesh geometry={nodes.seats_cream_chassis4_0.geometry} material={materials['chassis.4']} position={[-0.025, 0.257, 0.257]} />
              <mesh geometry={nodes.seats_cream_seats_cream2_0.geometry} material={materials['seats_cream.2']} />
              <mesh geometry={nodes.seats_cream_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.seats_green_seats_green0_0.geometry} material={materials['seats_green.0']} position={[0.088, 0.633, -0.08]} />
              <mesh geometry={nodes.seats_pattern_movsteer_104_0.geometry} material={materials['movsteer_1.0.4']} />
              <mesh geometry={nodes.seats_pattern_seats_pattern1_0.geometry} material={materials['seats_pattern.1']} position={[-0.022, 0.237, -0.325]} />
              <mesh geometry={nodes.sidebar_light_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.sidebar_light_glass_glass001_0.geometry} material={materials['glass.001']} />
              <mesh geometry={nodes.sidewall_chassis1_0.geometry} material={materials['chassis.1']} />
              <mesh geometry={nodes.sidewall_chassis3_0.geometry} material={materials['chassis.3']} />
              <mesh geometry={nodes.sidewall_chassis4_0.geometry} material={materials['chassis.4']} />
              <mesh geometry={nodes.sidewall_mb010_0.geometry} material={materials['mb01.0']} />
              <mesh geometry={nodes.sidewall_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.sidewall_movsteer_104_0.geometry} material={materials['movsteer_1.0.4']} />
              <mesh geometry={nodes.sidewall_sidewall1_0.geometry} material={materials['sidewall.1']} />
              <mesh geometry={nodes.sidewall_sidewall9_0.geometry} material={materials['sidewall.9']} />
              <mesh geometry={nodes.sidewall_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.sidewall_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.sidewall_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
              <mesh geometry={nodes.speedometer_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.speedometer_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.speedometer_movsteer_104_0.geometry} material={materials['movsteer_1.0.4']} />
              <mesh geometry={nodes.speedometer_speedometer3_0.geometry} material={materials['speedometer.3']} />
              <mesh geometry={nodes.speedometer_speedometer4_0.geometry} material={materials['speedometer.4']} />
              <mesh geometry={nodes.speedometer_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.speedometer_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.speedometer_glass_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.speedometer_symbols_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.tailights_r_mb010_0.geometry} material={materials['mb01.0']} />
              <mesh geometry={nodes.indicator_lr001_indicator_lr_0.geometry} material={materials.indicator_lr} />
              <mesh geometry={nodes.indicator_rr001_indicator_rr_0.geometry} material={materials.indicator_rr} />
              <mesh geometry={nodes.revlight_l_revlight_L_0.geometry} material={materials.revlight_L} />
              <mesh geometry={nodes.revlight_r_revlight_r_0.geometry} material={materials.revlight_r} />
              <mesh geometry={nodes.tailight_glass_glass001_0.geometry} material={materials['glass.001']} />
              <mesh geometry={nodes.tailight_glass_glass_0.geometry} material={materials.glass} />
              <mesh geometry={nodes.tailight_rr_right_rear_light_0.geometry} material={materials.right_rear_light} />
              <mesh geometry={nodes.taillight_lr_left_rear_light_0.geometry} material={materials.left_rear_light} />
              <mesh geometry={nodes.windscreen_glass002_0.geometry} material={materials['glass.002']} position={[0, -1.014, 0.925]} />
              <mesh geometry={nodes.windscreen_r_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.windscreen_r_windscreen_r0_0.geometry} material={materials['windscreen_r.0']} />
              <mesh geometry={nodes.windscreen_r_glass_glass002_0.geometry} material={materials['glass.002']} />
            </group>
            <group position={[-0.818, 0.793, 0.091]}>
              <group position={[0.824, 0.951, -0.557]}>
                <mesh geometry={nodes.indicator_lm001_indicator_lm_0.geometry} material={materials.indicator_lm} />
                <mesh geometry={nodes.indicator_lm_glass_glass_0.geometry} material={materials.glass} />
              </group>
              <mesh geometry={nodes.door_lf_chassis1_0.geometry} material={materials['chassis.1']} />
              <mesh geometry={nodes.door_lf_chassis4_0.geometry} material={materials['chassis.4']} />
              <mesh geometry={nodes.door_lf_mb010_0.geometry} material={materials['mb01.0']} />
              <mesh geometry={nodes.door_lf_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.door_lf_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.door_lf_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.door_lf_movsteer_104_0.geometry} material={materials['movsteer_1.0.4']} />
              <mesh geometry={nodes.door_lf_primary_0.geometry} material={materials.primary} position={[-0.094, 0.015, 0.081]} />
              <mesh geometry={nodes.door_lf_speedometer3_0.geometry} material={materials['speedometer.3']} />
              <mesh geometry={nodes.door_lf_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.door_lf_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.door_lf_glass_glass002_0.geometry} material={materials['glass.002']} />
            </group>
            <group position={[-0.831, -0.259, 0.096]}>
              <mesh geometry={nodes.door_lr_chassis1_0.geometry} material={materials['chassis.1']} />
              <mesh geometry={nodes.door_lr_chassis4_0.geometry} material={materials['chassis.4']} />
              <mesh geometry={nodes.door_lr_mb010_0.geometry} material={materials['mb01.0']} />
              <mesh geometry={nodes.door_lr_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.door_lr_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.door_lr_movsteer_104_0.geometry} material={materials['movsteer_1.0.4']} />
              <mesh geometry={nodes.door_lr_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.door_lr_speedometer3_0.geometry} material={materials['speedometer.3']} />
              <mesh geometry={nodes.door_lr_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.door_lr_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.door_lr_glass_glass002_0.geometry} material={materials['glass.002']} />
            </group>
            <group position={[0.829, 0.794, 0.092]}>
              <group position={[-0.823, 0.95, -0.558]}>
                <mesh geometry={nodes.indicator_rm001_indicator_rm_0.geometry} material={materials.indicator_rm} />
                <mesh geometry={nodes.indicator_rm_glass_glass_0.geometry} material={materials.glass} />
              </group>
              <mesh geometry={nodes.door_rf_chassis1_0.geometry} material={materials['chassis.1']} />
              <mesh geometry={nodes.door_rf_chassis4_0.geometry} material={materials['chassis.4']} />
              <mesh geometry={nodes.door_rf_mb010_0.geometry} material={materials['mb01.0']} />
              <mesh geometry={nodes.door_rf_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.door_rf_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.door_rf_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
              <mesh geometry={nodes.door_rf_movsteer_104_0.geometry} material={materials['movsteer_1.0.4']} />
              <mesh geometry={nodes.door_rf_primary_0.geometry} material={materials.primary} position={[0.148, 0.052, -0.162]} />
              <mesh geometry={nodes.door_rf_speedometer3_0.geometry} material={materials['speedometer.3']} />
              <mesh geometry={nodes.door_rf_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.door_rf_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.door_rf_glass_glass002_0.geometry} material={materials['glass.002']} />
            </group>
            <group position={[0.842, -0.259, 0.097]}>
              <mesh geometry={nodes.door_rr_chassis1_0.geometry} material={materials['chassis.1']} />
              <mesh geometry={nodes.door_rr_chassis4_0.geometry} material={materials['chassis.4']} />
              <mesh geometry={nodes.door_rr_mb010_0.geometry} material={materials['mb01.0']} />
              <mesh geometry={nodes.door_rr_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
              <mesh geometry={nodes.door_rr_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
              <mesh geometry={nodes.door_rr_movsteer_104_0.geometry} material={materials['movsteer_1.0.4']} />
              <mesh geometry={nodes.door_rr_primary_0.geometry} material={materials.primary} />
              <mesh geometry={nodes.door_rr_speedometer3_0.geometry} material={materials['speedometer.3']} />
              <mesh geometry={nodes.door_rr_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.door_rr_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.door_rr_glass_glass002_0.geometry} material={materials['glass.002']} />
            </group>
            <group position={[0.337, 0.313, 0.221]} rotation={[-0.387, 0, 0]}>
              <group position={[-0.002, 0.046, 0.029]} rotation={[0.004, 0, 0]}>
                <mesh geometry={nodes.movsteer_10_movsteer_100_0.geometry} material={materials['movsteer_1.0.0']} />
                <mesh geometry={nodes.movsteer_10_movsteer_101_0.geometry} material={materials['movsteer_1.0.1']} />
                <mesh geometry={nodes.movsteer_10_movsteer_103_0.geometry} material={materials['movsteer_1.0.3']} />
                <mesh geometry={nodes.movsteer_10_movsteer_104_0.geometry} material={materials['movsteer_1.0.4']} />
                <mesh geometry={nodes.movsteer_10_movsteer_106_0.geometry} material={materials['movsteer_1.0.6']} />
                <mesh geometry={nodes.movsteer_10_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
                <mesh geometry={nodes.movsteer_10_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              </group>
            </group>
          </group>
          <group position={[0.768, 1.203, -0.406]}>
            <group position={[0, -2.456, -0.027]}>
              <mesh geometry={nodes.wheel_rf001_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.wheel_rf001_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.wheel_rf001_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.wheel_rf001_wheel_rf3_0.geometry} material={materials['wheel_rf.3']} />
              <mesh geometry={nodes.wheel_rf001_wheel_rf4_0.geometry} material={materials['wheel_rf.4']} />
              <mesh geometry={nodes.wheel_rf001_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
            </group>
            <group position={[-1.534, -2.456, -0.027]} rotation={[-Math.PI, 0, 0]} scale={-1}>
              <mesh geometry={nodes.wheel_rf002_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.wheel_rf002_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.wheel_rf002_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.wheel_rf002_wheel_rf3_0.geometry} material={materials['wheel_rf.3']} />
              <mesh geometry={nodes.wheel_rf002_wheel_rf4_0.geometry} material={materials['wheel_rf.4']} />
              <mesh geometry={nodes.wheel_rf002_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
            </group>
            <group position={[-1.534, 0, 0]} rotation={[-Math.PI, 0, 0]} scale={-1}>
              <mesh geometry={nodes.wheel_rf003_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} />
              <mesh geometry={nodes.wheel_rf003_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
              <mesh geometry={nodes.wheel_rf003_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} />
              <mesh geometry={nodes.wheel_rf003_wheel_rf3_0.geometry} material={materials['wheel_rf.3']} position={[0.115, -0.023, 0]} />
              <mesh geometry={nodes.wheel_rf003_wheel_rf4_0.geometry} material={materials['wheel_rf.4']} />
              <mesh geometry={nodes.wheel_rf003_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
            </group>
            <mesh geometry={nodes.wheel_rf_wheel_rf0_0.geometry} material={materials['wheel_rf.0']} position={[-0.03, 0.034, -0.034]} />
            <mesh geometry={nodes.wheel_rf_wheel_rf1_0.geometry} material={materials['wheel_rf.1']} />
            <mesh geometry={nodes.wheel_rf_wheel_rf2_0.geometry} material={materials['wheel_rf.2']} position={[-0.067, 0.044, 0.018]} />
            <mesh geometry={nodes.wheel_rf_wheel_rf3_0.geometry} material={materials['wheel_rf.3']} position={[-0.061, 0.039, -0.043]} />
            <mesh geometry={nodes.wheel_rf_wheel_rf4_0.geometry} material={materials['wheel_rf.4']} />
            <mesh geometry={nodes.wheel_rf_wheel_rf5_0.geometry} material={materials['wheel_rf.5']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Swift-car.glb')